plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.4' // 안정적인 최신 버전으로 수정
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.goodsrun'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17) // 기획했던 Java 21 스펙으로 복구
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // 웹 API 생성 및 JSON 변환
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // JPA 및 DB 연동
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // Controller DTO 검증 (@Valid, @NotNull 등)
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // Redis 분산락 (선착순 래플 방어용)
    implementation 'org.redisson:redisson-spring-boot-starter:3.27.0'
    
    // MySQL DB 드라이버
    runtimeOnly 'com.mysql:mysql-connector-j'
    
    // 롬복 (어노테이션 기반 코드 자동 완성)
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    
    // 스프링 부트 통합 테스트 환경
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}